language: python
python:
- 2.6
- 2.7
- 3.3
before_install:
- sudo apt-get install freetds-dev
- pip install --use-mirrors pytest SQLAlchemy
- pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
- pip install Sphinx sphinx-rtd-theme
- pip --version
- time pip install --use-wheel --no-index --find-links=http://wheels.astropy.org/ --find-links=http://wheels2.astropy.org/ Cython
- "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
install:
- python setup.py install
script:
- . extra/travis_env.sh
- echo "\$PYMSSQL_TEST_DATABASE = \"$PYMSSQL_TEST_DATABASE\""
- py.test -v
- cd docs && test -z "$(make SPHINXOPTS='-q' html 2>&1 | egrep -w 'SEVERE:|ERROR:')"
branches:
  except:
    - 1.0
env:
  global:
  - secure: KQ7dawxyyp+skShD+iIT+D6qVaeKZVeZXDM+kpA5hvZNdDMI9iVSAUbVlg7Al26l18cSPCxkYNAsi1N4vsD7x0wGjsEAhC6mpytkc1Igwv0OppmjZI5BhxJWsGPEogzk78HM8JALG4SNhW3xGB0IQtqcV1GogbYmRqw+IDriGm0=
  - secure: bjCYROweKNsg7iZG4hyte7EkulP7ubENHQvOvZ6a4ojtj4AtorcP2G5ltq6wfVFbFCnsVc04ePujZx4PgDGxHnexTZkVhhwI66O/N482mytdCytje2flhXgQe8A9yw9FBYITm/BNjmTvTq9+ZKQYomLgxeYaJk5DcB5LFSB2Qns=
  - secure: P62aB5u8xOCZP5qX3lHZuQJNMrkMJCqwboRhtsxJz0m5LY77KO26xIb4DygnUJplx9wlWveZZ5u6bfzrDVkMECZ6jd195xWIwrbDokg8zGCVjcOEOCOGLdCUXChoD8wqYMuVMlefJxeR+w8gFPFbCyJjGeq1sKxsowUxH5HueNE=
  - secure: bMxRxhLnzxHyouQeQE6Ap8e6m70j5J2WKxcjRITKXEPN6UFWL+h+/EJbGKTG33g7ETKiCez8zyAtXQy8oGeHVbjCuvUhSIolI+wm/H7Rlo7FeoBH/wtbLutOsWyfYLqThc4MQZB/GDN/szzlN+H7SI4ciXSpaE5qWMXQIHrvYzg=
