language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
addons:
  apt:
    packages:
    - freetds-dev
before_install:
- travis_retry pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
- travis_retry pip install pytest SQLAlchemy
- travis_retry pip install Sphinx sphinx-rtd-theme
- pip --version
- travis_retry pip install --use-wheel Cython
install:
- if [[ $FREETDS_VERSION == '0.95' ]]; then export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1; fi
- python setup.py develop
script:
- . bin/travis_env.sh
- echo "\$PYMSSQL_TEST_DATABASE = \"$PYMSSQL_TEST_DATABASE\""
- py.test -v
- cd docs && test -z "$(make SPHINXOPTS='-q' html 2>&1 | egrep -w 'SEVERE:|ERROR:')"
- cd ..
branches:
  except:
  - 1.0
env:
  global:
  - secure: KQ7dawxyyp+skShD+iIT+D6qVaeKZVeZXDM+kpA5hvZNdDMI9iVSAUbVlg7Al26l18cSPCxkYNAsi1N4vsD7x0wGjsEAhC6mpytkc1Igwv0OppmjZI5BhxJWsGPEogzk78HM8JALG4SNhW3xGB0IQtqcV1GogbYmRqw+IDriGm0=
  - secure: bjCYROweKNsg7iZG4hyte7EkulP7ubENHQvOvZ6a4ojtj4AtorcP2G5ltq6wfVFbFCnsVc04ePujZx4PgDGxHnexTZkVhhwI66O/N482mytdCytje2flhXgQe8A9yw9FBYITm/BNjmTvTq9+ZKQYomLgxeYaJk5DcB5LFSB2Qns=
  - secure: P62aB5u8xOCZP5qX3lHZuQJNMrkMJCqwboRhtsxJz0m5LY77KO26xIb4DygnUJplx9wlWveZZ5u6bfzrDVkMECZ6jd195xWIwrbDokg8zGCVjcOEOCOGLdCUXChoD8wqYMuVMlefJxeR+w8gFPFbCyJjGeq1sKxsowUxH5HueNE=
  - secure: bMxRxhLnzxHyouQeQE6Ap8e6m70j5J2WKxcjRITKXEPN6UFWL+h+/EJbGKTG33g7ETKiCez8zyAtXQy8oGeHVbjCuvUhSIolI+wm/H7Rlo7FeoBH/wtbLutOsWyfYLqThc4MQZB/GDN/szzlN+H7SI4ciXSpaE5qWMXQIHrvYzg=
  matrix:
  - FREETDS_VERSION=0.91
  - FREETDS_VERSION=0.95
deploy:
  provider: pypi
  on:
    tags: true
    branch: stable-2.1.x
  password:
    secure: FnoI/4WfZUrpFYnrjuybA7boBF++E8mfNsXQlOZHEaF/hnfZfcAo97cSzAlkJnBppHDJ2XYZsk5xKmqEAnvQaRFXi/TVH1GPTPnffKGg2eCfkyTXBg9icvCx0YCLG1Rcinv7GiKWdzBTC2THWVXBSOIbao570tOBMtPZRgmrroE=
  user:
    secure: cXPF6Z3AsVdVbvnYcBUMAKme352y1j1E67U78WdN0mON7wZYYfz1wmcuwhjbWRUe0IzflTvOnAjwtkcMIO3espYACOhvX+zWxsqbq0vvAYZOVeoEaqoJVULWpUZNMappp/YLpjNMaVNQJScmRuUfl0HOB4jActF0AMiDd70tI7c=
  server: https://upload.pypi.io/legacy/
sudo: false
