language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
addons:
  apt:
    packages:
    - freetds-dev
    - gcc-multilib
    - libc6-dev-i386
before_install:
- travis_retry pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
- travis_retry pip install pytest SQLAlchemy
- travis_retry pip install Sphinx sphinx-rtd-theme
- pip --version
- travis_retry pip install Cython
install:
- if [[ $FREETDS_VERSION == '1.00' ]]; then dev/build_freetds_linux.sh; export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1; fi
- python setup.py develop
script:
- . dev/travis_env.sh
- echo "\$PYMSSQL_TEST_DATABASE = \"$PYMSSQL_TEST_DATABASE\""
- export TDSVER=7.1
- py.test -v
- cd docs && test -z "$(make SPHINXOPTS='-q' html 2>&1 | egrep -w 'SEVERE:|ERROR:')"
- cd ..
branches:
  except:
  - 1.0
env:
  global:
  - secure: KQ7dawxyyp+skShD+iIT+D6qVaeKZVeZXDM+kpA5hvZNdDMI9iVSAUbVlg7Al26l18cSPCxkYNAsi1N4vsD7x0wGjsEAhC6mpytkc1Igwv0OppmjZI5BhxJWsGPEogzk78HM8JALG4SNhW3xGB0IQtqcV1GogbYmRqw+IDriGm0=
  - secure: bjCYROweKNsg7iZG4hyte7EkulP7ubENHQvOvZ6a4ojtj4AtorcP2G5ltq6wfVFbFCnsVc04ePujZx4PgDGxHnexTZkVhhwI66O/N482mytdCytje2flhXgQe8A9yw9FBYITm/BNjmTvTq9+ZKQYomLgxeYaJk5DcB5LFSB2Qns=
  - secure: P62aB5u8xOCZP5qX3lHZuQJNMrkMJCqwboRhtsxJz0m5LY77KO26xIb4DygnUJplx9wlWveZZ5u6bfzrDVkMECZ6jd195xWIwrbDokg8zGCVjcOEOCOGLdCUXChoD8wqYMuVMlefJxeR+w8gFPFbCyJjGeq1sKxsowUxH5HueNE=
  - secure: bMxRxhLnzxHyouQeQE6Ap8e6m70j5J2WKxcjRITKXEPN6UFWL+h+/EJbGKTG33g7ETKiCez8zyAtXQy8oGeHVbjCuvUhSIolI+wm/H7Rlo7FeoBH/wtbLutOsWyfYLqThc4MQZB/GDN/szzlN+H7SI4ciXSpaE5qWMXQIHrvYzg=
  matrix:
  - FREETDS_VERSION=0.91
  - FREETDS_VERSION=1.00
deploy:
  provider: pypi
  on:
    tags: true
    branch: stable-2.1.x
  password:
    secure: BjXHmBDhVSJiiwePyLha3+ZuEzH4OVn2PrKzxqaXw4EohQoUfTALzTgYYjfowD65s2uioYkswAjFEctBcQ8Db0qtl4cy+IDKG50Q9o95k9gPPTXXXtaMMLm9aFGqlc6Ks8T0iYsR8nC0fLBQAnuoLWfaP0w7LtzK4tjfSuuxYx4=
  user:
    secure: iZTbCXCjzQYrAINmxEjpcp96Q2AO7NesY/RthiaIOCJNjTWiJBHZ4WhyLGLBsdixMmIxaxAoJ+ZyPjIMaQ9KQXVlj8XTiVBfcAJThRHSQyrGqEt60n7RCWjXOfBUJl7A/KszFeBVzfglIetSYUTjCjJdtc6ZaJlXm+AIVuYnq4w=
  server: https://test.pypi.org/legacy/
  distributions: "bdist_wheel"
sudo: false
