name: Wheels

on:
  push:
    branches:
        - '**'
    paths-ignore:
        - docs/**
        - ChangeLog*
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
        - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  pull_request:
    branches:
        - '**'
    paths-ignore:
        - docs/**
        - ChangeLog*

  workflow_dispatch:

jobs:

  build_sdist:

    name: SDist
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Build sdist
        run: |
            python -m pip install build
            python -m build --sdist --outdir wheelhouse

      - uses: actions/upload-artifact@v6
        with:
          name: pymssql-sdist-${{ github.sha }}
          path: wheelhouse

  build-wheels-matrix:
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: pip install cibuildwheel==3.1.4
      - id: set-matrix
        run: |
          MATRIX_INCLUDE=$(
            {
              cibuildwheel --print-build-identifiers --platform linux --archs x86_64 | grep cp |  jq -nRc '{"only": inputs, "os": "ubuntu-latest"}'
            } | jq -sc
          )
          echo "include=$MATRIX_INCLUDE" >> $GITHUB_OUTPUT

  build_wheels:

    needs: build-wheels-matrix
    name: ${{ matrix.only }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.build-wheels-matrix.outputs.include) }}

    services:
      SQLServer:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sqlServerPassw0rd
        ports:
          - 1433:1433

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pypa/cibuildwheel@v3.3.0
        with:
          only: ${{ matrix.only }}
        env:
          #CIBW_BUILD_VERBOSITY: 1
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.only }}
          path: wheelhouse

  build_wheels_2:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, macos-14, macos-15-intel]
        arch: [auto]

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: wheelhouse

  build_wheels_windows:

    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        arch: [AMD64, x86]

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install OpenSSL x86
        if: matrix.arch == 'x86'
        run: choco install openssl --forcex86 --version=1.1.1.2100

      - name: Install OpenSSL AMD64
        if: matrix.arch == 'AMD64'
        run: choco install openssl --version=3.1.1

      - name: Install gperf
        run: choco install gperf

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: wheelhouse

  merge_wheels:
    needs: [build_wheels, build_wheels_2, build_wheels_windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v6
        with:
          name: wheels
          separate-directories: false
          delete-merged: false

  check_wheels:
    needs: [merge_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: wheels
          path: dist/

      - name: Check wheels
        run: |
            # upgrade packaging for PEP 639
            python -m pip install packaging>=24.2 --upgrade
            python -m pip install twine --upgrade
            python -m twine check --strict dist/*

  upload-wheels:
    needs: [check_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: wheels
          path: dist/

      - name: Publish wheels and sdist
        if: github.repository_owner == 'pymssql' && startsWith(github.ref, 'refs/tags/v')
        run: |
            # upgrade packaging for PEP 639
            python -m pip install packaging>=24.2 --upgrade
            python -m pip install twine --upgrade
            twine upload --skip-existing -u __token__ -p ${{secrets.PYMSSQL_PYPI_TOKEN}} dist/*

      #- name: Publish wheels and sdist on test.pypi.org
        #if: github.repository_owner == 'pymssql' && github.ref == 'refs/heads/master'
        #run: |
            ## upgrade packaging for PEP 639
            #python -m pip install packaging>=24.2 --upgrade
            #python -m pip install twine --upgrade
            #twine upload --skip-existing -u __token__ -p ${{secrets.PYMSSQL_TEST_PYPI_TOKEN}} --repository-url=https://test.pypi.org/legacy/ dist/*
